version: '3.8'

services:
  stellar-os:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stellar_os_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always